### DISCUSSION TITLE
Rethinking Themes

### DISCUSSION THREAD

**Discussion by Nerixyz** [Chatterino/chatterino2#4447] [Ideas] [answered]
Theming in Chatterino is currently hard. This is especially visible when changing theme values (see #4140). It turns out, that, in order to support multiple themes, one needs to make specific adjustments for these themes. Especially, handling light and dark themes without checking for the current theme is often not enough, as they have different needs for contrast & saturation, so [one needs to branch on the theme](https://github.com/Chatterino/chatterino2/blob/01a4861d7602b75b1f553f3adc9e6e622761c089/src/singletons/Theme.cpp#L129-L167). The `Theme.cpp` in general feels like tech debt - e.g. there's a [`hue`](https://github.com/Chatterino/chatterino2/blob/01a4861d7602b75b1f553f3adc9e6e622761c089/src/singletons/Theme.hpp#L142) setting, that's only applied to the window-border, [that's never actually used anywhere](https://github.com/search?q=repo%3AChatterino%2Fchatterino2+borderFocused&type=code) and there are four different ways to check if the current theme is a light theme (`isLight_`, `flat`, `isLight`, `this->isLightTheme()`).

Then there's the feature request to [support custom themes](https://github.com/Chatterino/chatterino2/issues/2237). This isn't possible with the current system.

I think one decent indicator for an extensible theming system is the usage/existence of the `isLightTheme` method. It should only be used to select icons. In an ideal world, there shouldn't be any hardcoded colors.

---

I'm proposing a new theme system, similar to how [Telegram Desktop](https://github.com/telegramdesktop/tdesktop) does it.
Themes are loaded from files (there's still one base theme). The `White`, `Light`, `Dark` and `Black` themes are shipped in the executable (as resources).

I made an example branch [here](https://github.com/nerixyz/chatterino2/tree/refactor/theme) ([diff](https://github.com/Nerixyz/chatterino2/commit/bdd576331dd6a2b0b13f740bdd51f9e053f33f5a)).

The most controversial change is probably the addition of _some_ style & code generator (similar to [`desktop-app/codegen/style`](https://github.com/desktop-app/codegen/tree/master/codegen/style)). The generator I used is [`cstylegen`](https://github.com/nerixyz/cstylegen).

The main benefits of having another generator (over a manual implementation) are

1. Allowing users that know CSS (the input format) to easily contribute (the format supports regular CSS colors and variables).
2. Simple deserialization at runtime.
3. Automatic checking of themes (not implemented yet).

The input themes are "regular" CSS files (with two additional @-rules added: `@chatterino`, `@nest`).

<details>
<summary>Example Dark.css</summary>

```css
@chatterino {
  author: "Forsen";
  icon-set: "dark";
}

:root {
  --gray50: #555555;
  --gray100: #6b6b6b; /* 0.6 */
  --gray200: #616161; /* 0.65 */
  --gray300: #575757; /* 0.7 */
  --gray400: #454545; /* 0.78 */
  --gray500: #424242; /* 0.79 */
  --gray600: #383838; /* 0.85 */
  --gray700: #2e2e2e; /* 0.9 */
  --gray800: #242424; /* 0.95 */
  --gray900: #212121; /* 0.96 */
  --gray950: #1a1a1a; /* 1.0 */

  --text-bright: #fff;
  --text: #eee;
  --text-dimmed: #aaa;

  --highlight-color: #ee6166;
  --sub-color: #c466ff;

  --link-text-color: #4286f4;
  --system-text-color: #8c7f7f;
  --placeholder-text-color: #5d5555;

  --scrollbar-thumb: #b3b3b3;
  --scrollbar-thumb-selected: #a6a6a6;

  --split-header-selected: hsl(210, 100%, 70%);

  --window-bg: #111;

  --tab-bg: #252525;
  --tab-bg-selected: #555555;

  --accent: #00aeef;
}

Tabs {
  border: white;
  divider-line: var(--tab-bg-selected);
  @nest regular {
    text: var(--text-dimmed);
    @nest backgrounds {
      regular: var(--tab-bg);
      hover: var(--tab-bg);
      unfocused: var(--tab-bg);
    }
    @nest line {
      regular: var(--gray400);
      hover: var(--gray400);
      unfocused: var(--gray400);
    }
  }

  @nest new-message {
    text: var(--text);
    @nest backgrounds {
      regular: var(--tab-bg);
      hover: var(--tab-bg);
      unfocused: var(--tab-bg);
    }
    @nest line {
      regular: #888;
      hover: #888;
      unfocused: #888;
    }
  }

  @nest highlighted {
    text: var(--text);
    @nest backgrounds {
      regular: var(--tab-bg);
      hover: var(--tab-bg);
      unfocused: var(--tab-bg);
    }
    @nest line {
      regular: var(--highlight-color);
      hover: var(--highlight-color);
      unfocused: var(--highlight-color);
    }
  }

  @nest selected {
    text: var(--text-bright);
    @nest backgrounds {
      regular: var(--tab-bg-selected);
      hover: var(--tab-bg-selected);
      unfocused: var(--tab-bg-selected);
    }
    @nest line {
      regular: var(--accent);
      hover: var(--accent);
      unfocused: var(--accent);
    }
  }
}

Messages {
  disabled: hsla(0, 0%, 10%, 0.6);
  selection: hsla(0, 0%, 100%, 0.251);
  highlight-animation-start: hsla(0, 0%, 90%, 0.431);
  highlight-animation-end: hsla(0, 0%, 90%, 0);
  @nest text-colors {
    regular: var(--text-bright);
    caret: var(--text-bright);
    link: var(--link-text-color);
    system: var(--system-text-color);
    chat-placeholder: var(--placeholder-text-color);
  }
  @nest backgrounds {
    regular: var(--gray950);
    alternate: var(--gray900);
  }
}

Scrollbars {
  background: transparent;
  thumb: var(--scrollbar-thumb);
  thumbselected: var(--scrollbar-thumb-selected);
  @nest highlights {
    highlight: var(--highlight-color);
    subscription: var(--sub-color);
  }
}

Tooltip {
  text: var(--text-bright);
  background: black;
}

Splits {
  message-seperator: var(--gray600);
  background: var(--gray950);
  drop-preview: hsla(205, 100%, 50%, 0.18);
  drop-preview-border: hsl(205, 100%, 50%);
  drop-target-rect: hsla(205, 100%, 50%, 0);
  drop-target-rect-border: hsla(205, 100%, 50%, 0);
  resize-handle: hsla(205, 100%, 50%, 0.44);
  resize-handle-background: hsla(205, 100%, 50%, 0.125);

  @nest header {
    border: var(--gray600);
    focused-border: var(--gray500);
    background: var(--gray700);
    focused-background: var(--gray500);
    text: var(--text-bright);
    focused-text: var(--split-header-selected);
  }

  @nest input {
    border: var(--gray950);
    background: var(--gray800);
    selection: transparent; /* unused? */
    focused-line: var(--highlight-color);
    text: var(--highlight-color);
  }
}

Colors {
  accent-color: var(--accent);
}

Window {
  text: var(--text);
  background: var(--window-bg);
  border-focused: var(--accent);
  border-unfocused: var(--gray100);
}
```
</details>

This will be compiled to a `.c2theme` file, which is basically a `key=value` format.

<details>
<summary>Compiled Dark.c2theme</summary>

```
@meta
author=Forsen
iconset=dark
@colors
tabs.highlighted.line.hover=#ffee6166
tabs.newmessage.text=#ffeeeeee
tabs.selected.text=#ffffffff
window.borderunfocused=#ff6b6b6b
splits.header.background=#ff2e2e2e
window.text=#ffeeeeee
tabs.highlighted.backgrounds.unfocused=#ff252525
messages.disabled=#991a1a1a
tabs.selected.backgrounds.hover=#ff555555
messages.highlightanimationend=#00e6e6e6
splits.header.focusedborder=#ff424242
splits.input.text=#ffee6166
tooltip.text=#ffffffff
tabs.selected.line.hover=#ff00aeef
tabs.highlighted.line.regular=#ffee6166
messages.textcolors.link=#ff4286f4
tabs.dividerline=#ff555555
tabs.newmessage.line.unfocused=#ff888888
splits.header.focusedtext=#ff66b3ff
scrollbars.thumb=#ffb3b3b3
tabs.highlighted.text=#ffeeeeee
tabs.newmessage.backgrounds.hover=#ff252525
tabs.selected.line.regular=#ff00aeef
splits.input.selection=#00000000
splits.background=#ff1a1a1a
tabs.newmessage.backgrounds.regular=#ff252525
splits.droppreview=#2e0095ff
tooltip.background=#ff000000
splits.header.text=#ffffffff
scrollbars.highlights.subscription=#ffc466ff
messages.textcolors.system=#ff8c7f7f
tabs.regular.text=#ffaaaaaa
tabs.highlighted.backgrounds.regular=#ff252525
colors.accentcolor=#ff00aeef
messages.selection=#40ffffff
splits.resizehandlebackground=#200095ff
tabs.selected.line.unfocused=#ff00aeef
tabs.regular.line.regular=#ff454545
messages.textcolors.chatplaceholder=#ff5d5555
tabs.regular.backgrounds.regular=#ff252525
messages.textcolors.regular=#ffffffff
tabs.highlighted.backgrounds.hover=#ff252525
tabs.regular.line.hover=#ff454545
splits.droptargetrectborder=#000095ff
tabs.regular.backgrounds.hover=#ff252525
tabs.newmessage.line.hover=#ff888888
window.borderfocused=#ff00aeef
splits.input.background=#ff242424
tabs.selected.backgrounds.unfocused=#ff555555
splits.droppreviewborder=#ff0095ff
scrollbars.thumbselected=#ffa6a6a6
tabs.newmessage.line.regular=#ff888888
messages.textcolors.caret=#ffffffff
splits.input.focusedline=#ffee6166
messages.backgrounds.alternate=#ff212121
messages.highlightanimationstart=#6ee6e6e6
tabs.selected.backgrounds.regular=#ff555555
tabs.regular.line.unfocused=#ff454545
tabs.highlighted.line.unfocused=#ffee6166
tabs.border=#ffffffff
messages.backgrounds.regular=#ff1a1a1a
splits.input.border=#ff1a1a1a
scrollbars.highlights.highlight=#ffee6166
tabs.regular.backgrounds.unfocused=#ff252525
splits.droptargetrect=#000095ff
tabs.newmessage.backgrounds.unfocused=#ff252525
splits.header.border=#ff383838
splits.messageseperator=#ff383838
window.background=#ff111111
scrollbars.background=#00000000
splits.header.focusedbackground=#ff424242
splits.resizehandle=#700095ff
```
</details>

This was one part of the generator. The other part is generating a header and source file for a given theme layout (in theory this could be done manually).

<details>
<summary>GeneratedTheme.hpp</summary>

```cpp
#include <QColor>
#include <QByteArray>

namespace chatterino::theme {
class GeneratedTheme {
public:
	struct TabColors {
		
		struct {
			QColor regular;
			QColor hover;
			QColor unfocused;
		} backgrounds;
		
		struct {
			QColor regular;
			QColor hover;
			QColor unfocused;
		} line;
		QColor text;
	};
	
	struct {
		QColor accentColor;
	} colors;
	
	struct {
		
		struct {
			QColor regular;
			QColor alternate;
		} backgrounds;
		QColor disabled;
		QColor highlightAnimationEnd;
		QColor highlightAnimationStart;
		QColor selection;
		
		struct {
			QColor regular;
			QColor caret;
			QColor link;
			QColor system;
			QColor chatPlaceholder;
		} textColors;
	} messages;
	
	struct {
		QColor background;
		
		struct {
			QColor highlight;
			QColor subscription;
		} highlights;
		QColor thumb;
		QColor thumbSelected;
	} scrollbars;
	
	struct {
		QColor background;
		QColor dropPreview;
		QColor dropPreviewBorder;
		QColor dropTargetRect;
		QColor dropTargetRectBorder;
		
		struct {
			QColor border;
			QColor focusedBorder;
			QColor background;
			QColor focusedBackground;
			QColor text;
			QColor focusedText;
		} header;
		
		struct {
			QColor border;
			QColor background;
			QColor selection;
			QColor focusedLine;
			QColor text;
		} input;
		QColor messageSeperator;
		QColor resizeHandle;
		QColor resizeHandleBackground;
	} splits;
	
	struct {
		QColor border;
		QColor dividerLine;
		TabColors highlighted;
		TabColors newMessage;
		TabColors regular;
		TabColors selected;
	} tabs;
	
	struct {
		QColor text;
		QColor background;
	} tooltip;
	
	struct {
		QColor text;
		QColor background;
		QColor borderUnfocused;
		QColor borderFocused;
	} window;
	GeneratedTheme();

protected:
	bool setColor(const QByteArray &name, QColor color);
	void reset();
	void applyChanges();

private:
	QColor colors_[72];
};
}  // namespace chatterino::theme
```
</details>

<details>
<summary>GeneratedTheme.cpp</summary>

```cpp
#include "GeneratedTheme.hpp"
#include <QColor>
#include <QString>
#include <QByteArray>
#include <QMap>
#include <cstring>

namespace {
	int getDataIndex(const QByteArray &name);
} //  namespace
namespace chatterino::theme {
GeneratedTheme::GeneratedTheme() {
	this->reset();
	this->applyChanges();
}
void GeneratedTheme::applyChanges() {
	const auto d = [this](size_t i) -> const QColor& { return this->colors_[i]; };
	this->colors = {
		d(0),
	};
	this->messages = {
		{
			d(1),
			d(2),
		},
		d(3),
		d(4),
		d(5),
		d(6),
		{
			d(7),
			d(8),
			d(9),
			d(10),
			d(11),
		},
	};
	this->scrollbars = {
		d(12),
		{
			d(13),
			d(14),
		},
		d(15),
		d(16),
	};
	this->splits = {
		d(17),
		d(18),
		d(19),
		d(20),
		d(21),
		{
			d(22),
			d(23),
			d(24),
			d(25),
			d(26),
			d(27),
		},
		{
			d(28),
			d(29),
			d(30),
			d(31),
			d(32),
		},
		d(33),
		d(34),
		d(35),
	};
	this->tabs = {
		d(36),
		d(37),
		{
			{
				d(38),
				d(39),
				d(40),
			},
			{
				d(41),
				d(42),
				d(43),
			},
			d(44),
		},
		{
			{
				d(45),
				d(46),
				d(47),
			},
			{
				d(48),
				d(49),
				d(50),
			},
			d(51),
		},
		{
			{
				d(52),
				d(53),
				d(54),
			},
			{
				d(55),
				d(56),
				d(57),
			},
			d(58),
		},
		{
			{
				d(59),
				d(60),
				d(61),
			},
			{
				d(62),
				d(63),
				d(64),
			},
			d(65),
		},
	};
	this->tooltip = {
		d(66),
		d(67),
	};
	this->window = {
		d(68),
		d(69),
		d(70),
		d(71),
	};
	this->reset();
}
void GeneratedTheme::reset() {
	this->colors_[0] = {0, 174, 239, 255};
	this->colors_[1] = {26, 26, 26, 255};
	this->colors_[2] = {33, 33, 33, 255};
	this->colors_[3] = {26, 26, 26, 153};
	this->colors_[4] = {230, 230, 230, 0};
	this->colors_[5] = {230, 230, 230, 110};
	this->colors_[6] = {255, 255, 255, 64};
	this->colors_[7] = {255, 255, 255, 255};
	this->colors_[8] = {255, 255, 255, 255};
	this->colors_[9] = {66, 134, 244, 255};
	this->colors_[10] = {140, 127, 127, 255};
	this->colors_[11] = {93, 85, 85, 255};
	this->colors_[12] = {0, 0, 0, 0};
	this->colors_[13] = {238, 97, 102, 255};
	this->colors_[14] = {196, 102, 255, 255};
	this->colors_[15] = {179, 179, 179, 255};
	this->colors_[16] = {166, 166, 166, 255};
	this->colors_[17] = {26, 26, 26, 255};
	this->colors_[18] = {0, 149, 255, 46};
	this->colors_[19] = {0, 149, 255, 255};
	this->colors_[20] = {0, 149, 255, 0};
	this->colors_[21] = {0, 149, 255, 0};
	this->colors_[22] = {56, 56, 56, 255};
	this->colors_[23] = {66, 66, 66, 255};
	this->colors_[24] = {46, 46, 46, 255};
	this->colors_[25] = {66, 66, 66, 255};
	this->colors_[26] = {255, 255, 255, 255};
	this->colors_[27] = {102, 179, 255, 255};
	this->colors_[28] = {26, 26, 26, 255};
	this->colors_[29] = {36, 36, 36, 255};
	this->colors_[30] = {0, 0, 0, 0};
	this->colors_[31] = {238, 97, 102, 255};
	this->colors_[32] = {238, 97, 102, 255};
	this->colors_[33] = {56, 56, 56, 255};
	this->colors_[34] = {0, 149, 255, 112};
	this->colors_[35] = {0, 149, 255, 32};
	this->colors_[36] = {255, 255, 255, 255};
	this->colors_[37] = {85, 85, 85, 255};
	this->colors_[38] = {37, 37, 37, 255};
	this->colors_[39] = {37, 37, 37, 255};
	this->colors_[40] = {37, 37, 37, 255};
	this->colors_[41] = {238, 97, 102, 255};
	this->colors_[42] = {238, 97, 102, 255};
	this->colors_[43] = {238, 97, 102, 255};
	this->colors_[44] = {238, 238, 238, 255};
	this->colors_[45] = {37, 37, 37, 255};
	this->colors_[46] = {37, 37, 37, 255};
	this->colors_[47] = {37, 37, 37, 255};
	this->colors_[48] = {136, 136, 136, 255};
	this->colors_[49] = {136, 136, 136, 255};
	this->colors_[50] = {136, 136, 136, 255};
	this->colors_[51] = {238, 238, 238, 255};
	this->colors_[52] = {37, 37, 37, 255};
	this->colors_[53] = {37, 37, 37, 255};
	this->colors_[54] = {37, 37, 37, 255};
	this->colors_[55] = {69, 69, 69, 255};
	this->colors_[56] = {69, 69, 69, 255};
	this->colors_[57] = {69, 69, 69, 255};
	this->colors_[58] = {170, 170, 170, 255};
	this->colors_[59] = {85, 85, 85, 255};
	this->colors_[60] = {85, 85, 85, 255};
	this->colors_[61] = {85, 85, 85, 255};
	this->colors_[62] = {0, 174, 239, 255};
	this->colors_[63] = {0, 174, 239, 255};
	this->colors_[64] = {0, 174, 239, 255};
	this->colors_[65] = {255, 255, 255, 255};
	this->colors_[66] = {255, 255, 255, 255};
	this->colors_[67] = {0, 0, 0, 255};
	this->colors_[68] = {238, 238, 238, 255};
	this->colors_[69] = {17, 17, 17, 255};
	this->colors_[70] = {107, 107, 107, 255};
	this->colors_[71] = {0, 174, 239, 255};
}
bool GeneratedTheme::setColor(const QByteArray &name, QColor color) {
	auto idx = getDataIndex(name);
	if (idx < 0) return false;
	this->colors_[idx] = color;
	return true;
}
} //  namespace chatterino::theme
namespace {
int getDataIndex(const QByteArray &name) {
	static const QMap<QByteArray, size_t> dataMap = {
		{"colors.accentcolor", 0},
		{"messages.backgrounds.regular", 1},
		{"messages.backgrounds.alternate", 2},
		{"messages.disabled", 3},
		{"messages.highlightanimationend", 4},
		{"messages.highlightanimationstart", 5},
		{"messages.selection", 6},
		{"messages.textcolors.regular", 7},
		{"messages.textcolors.caret", 8},
		{"messages.textcolors.link", 9},
		{"messages.textcolors.system", 10},
		{"messages.textcolors.chatplaceholder", 11},
		{"scrollbars.background", 12},
		{"scrollbars.highlights.highlight", 13},
		{"scrollbars.highlights.subscription", 14},
		{"scrollbars.thumb", 15},
		{"scrollbars.thumbselected", 16},
		{"splits.background", 17},
		{"splits.droppreview", 18},
		{"splits.droppreviewborder", 19},
		{"splits.droptargetrect", 20},
		{"splits.droptargetrectborder", 21},
		{"splits.header.border", 22},
		{"splits.header.focusedborder", 23},
		{"splits.header.background", 24},
		{"splits.header.focusedbackground", 25},
		{"splits.header.text", 26},
		{"splits.header.focusedtext", 27},
		{"splits.input.border", 28},
		{"splits.input.background", 29},
		{"splits.input.selection", 30},
		{"splits.input.focusedline", 31},
		{"splits.input.text", 32},
		{"splits.messageseperator", 33},
		{"splits.resizehandle", 34},
		{"splits.resizehandlebackground", 35},
		{"tabs.border", 36},
		{"tabs.dividerline", 37},
		{"tabs.highlighted.backgrounds.regular", 38},
		{"tabs.highlighted.backgrounds.hover", 39},
		{"tabs.highlighted.backgrounds.unfocused", 40},
		{"tabs.highlighted.line.regular", 41},
		{"tabs.highlighted.line.hover", 42},
		{"tabs.highlighted.line.unfocused", 43},
		{"tabs.highlighted.text", 44},
		{"tabs.newmessage.backgrounds.regular", 45},
		{"tabs.newmessage.backgrounds.hover", 46},
		{"tabs.newmessage.backgrounds.unfocused", 47},
		{"tabs.newmessage.line.regular", 48},
		{"tabs.newmessage.line.hover", 49},
		{"tabs.newmessage.line.unfocused", 50},
		{"tabs.newmessage.text", 51},
		{"tabs.regular.backgrounds.regular", 52},
		{"tabs.regular.backgrounds.hover", 53},
		{"tabs.regular.backgrounds.unfocused", 54},
		{"tabs.regular.line.regular", 55},
		{"tabs.regular.line.hover", 56},
		{"tabs.regular.line.unfocused", 57},
		{"tabs.regular.text", 58},
		{"tabs.selected.backgrounds.regular", 59},
		{"tabs.selected.backgrounds.hover", 60},
		{"tabs.selected.backgrounds.unfocused", 61},
		{"tabs.selected.line.regular", 62},
		{"tabs.selected.line.hover", 63},
		{"tabs.selected.line.unfocused", 64},
		{"tabs.selected.text", 65},
		{"tooltip.text", 66},
		{"tooltip.background", 67},
		{"window.text", 68},
		{"window.background", 69},
		{"window.borderunfocused", 70},
		{"window.borderfocused", 71},
	};
	return dataMap.value(name, -1);
}
} //  namespace
```
</details>

**Why not do it like...?**

I haven't really found many applications having a theme system that could be applied here. One application I found was [OBS](https://github.com/obsproject/obs-studio). They're [basically parsing CSS](https://github.com/obsproject/obs-studio/blob/0a36dc9d80a95c63ea54c8fc0aaa4ce1b6b28909/UI/obs-app.cpp#L1113). I don't think this approach is reasonable for Chatterino. The final Chatterino executable shouldn't contain a (half compliant) CSS parser. Especially because Chatterino's theme has nested colors.

**Further work**

These themes don't apply to Qt's palette. This would be the next step, as well as using [`palette`](https://doc.qt.io/qt-5/stylesheet-reference.html#paletterole) in the settings stylesheet.

---

What do you think about this approach? Are there other approaches you know that would be viable here?
